### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by ilanZeek** [pettazz/pygooglevoice#15]
The issue is in voice.py line 75:
galx = re.search(r"name=\"GALX\"\s+type=\"hidden\"\s+value=\"(.+)\"", content).group(1)

Google changed the order of the attributes, so "type" is now before "name". This works:
galx = re.search(r"\type=\"hidden\"\s+name=\"GALX\"\s+value=\"(.+)\"", content).group(1)

**Comment by twbarber** [comment]
Opened a [pull request]( https://github.com/pettazz/pygooglevoice/pull/16) with your fix.

**Comment by edmond25** [comment]
galx = re.search(r"type=\"hidden\"\s+name=\"GALX\"\s+value=\"(.+)\"", content).group(1)

Just remove \ from (r"\type
