### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by man000** [pettazz/pygooglevoice#48]
Hi! To keep it short.
I can't login.
Below traceback:

Traceback (most recent call last):
  File "C:\Documents and Settings\Administrator\Desktop\insideout\gv.py", line 35, in <module>
    voice.login(email, password)
  File "C:\Python27\lib\site-packages\googlevoice\voice.py", line 76, in login
    result = self.__do_page('login_post', {'Email': email, 'Passwd': passwd, 'gxf': gxf})
  File "C:\Python27\lib\site-packages\googlevoice\voice.py", line 279, in __do_page

**Comment by gkuenning** [comment]
Although it was thoughtful of you to keep it short, I think you 
kept it a bit *too* short.  There should be some additional Python 
information about what went wrong, e.g. an exception name.

In my copy of the source, line 279 of voice.py is an if statement 
that shouldn't ever produce an error.

Can you please paste the full output (with passwords erased, of 
course!)?

> Hi! To keep it short.
> I can't login.
> Below traceback:
>
> Traceback (most recent call last):
>   File "C:\Documents and 
>   Settings\Administrator\Desktop\insideout\gv.py", line 35, in 
>   <module>
>     voice.login(email, password)
>   File "C:\Python27\lib\site-packages\googlevoice\voice.py", 
>   line 76, in login
>     result = self.__do_page('login_post', {'Email': email, 
>     'Passwd': passwd, 'gxf': gxf})
>   File "C:\Python27\lib\site-packages\googlevoice\voice.py", 
>   line 279, in __do_page
>
> -- 
> You are receiving this because you are subscribed to this 
> thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pettazz/pygooglevoice/issues/48

-- 
    Geoff Kuenning   geoff@cs.hmc.edu 
    http://www.cs.hmc.edu/~geoff/

Keep trying, and keep the best.

**Comment by chris001** [comment]
@man000 
Which version you running?
Where did install it from - github, other download?
How did you install it?
Which windows OS you running?
Which version python you running?

**Comment by man000** [comment]
I installed windows 2003 server x64
CPU : Intel Xeon
32gb ram
Python 2.7
And I installed pygooglevoice through pip

Full code below:

from googlevoice import Voice
import sys
import BeautifulSoup


def extractsms(htmlsms) :
    """
    extractsms  --  extract SMS messages from BeautifulSoup tree of Google Voice SMS HTML.

    Output is a list of dictionaries, one per message.
    """
    msgitems = []										# accum message items here
    #	Extract all conversations by searching for a DIV with an ID at top level.
    tree = BeautifulSoup.BeautifulSoup(htmlsms)			# parse HTML into tree
    conversations = tree.findAll("div",attrs={"id" : True},recursive=False)
    for conversation in conversations :
        #	For each conversation, extract each row, which is one SMS message.
        rows = conversation.findAll(attrs={"class" : "gc-message-sms-row"})
        for row in rows :								# for all rows
            #	For each row, which is one message, extract all the fields.
            msgitem = {"id" : conversation["id"]}		# tag this message with conversation ID
            spans = row.findAll("span",attrs={"class" : True}, recursive=False)
            for span in spans :							# for all spans in row
                cl = span["class"].replace('gc-message-sms-', '')
                msgitem[cl] = (" ".join(span.findAll(text=True))).strip()	# put text in dict
            msgitems.append(msgitem)					# add msg dictionary to list
    return msgitems
    

#define login details
email = 'user'
password = 'mypass'
go = True
voice = Voice()
voice.login(email, password)
'''
while go:
    
    voice.sms()
    for msg in extractsms(voice.sms.html):
        if msg['from']:
            msgtosend = "From : " + msg['from'] + "\n" + msg['text']
            print msgtosend
        else:
            print "no msg\n"
    


    for message in voice.sms().messages:
        message.delete(message['id'])





'''


#voice.send_sms("+mynum", "its me testing")

**Comment by chris001** [comment]
@man000 
The version on pypi was uploaded to pypi on Aug 24, 2016. It's way out of date.
You can download the one from my organization's repo it's the most up to date.
To do this, you just run these commands (this is the linux commands, the windows commands are kind of similar):
```
cd ~
git clone https://github.com/EspaceNetworks/pygooglevoice
cd pygooglevoice
pip install -r requirements.txt
python setup.py install
cp -p bin/gvoice /usr/bin/.
exit
```

**Comment by man000** [comment]
Thanks its worked many thanks

**Comment by chris001** [comment]
Note to self, take over the `pip` repo so we won't have users having issues from running the old version!
