### ISSUE TITLE
Question about Authentication

### ISSUE THREAD

**Issue by n8carrier** [pettazz/pygooglevoice#5]
Sorry, I'm a pretty novice developer. I'm using Google App Engine which allows users to login to my app with their Google Account.

Is there a way to log them into pygooglevoice using those credentials?

Or, is there a way to encrypt their password if they provide it, rather than sending it to pygooglevoice in plain text?

**Comment by chris001** [comment]
Doesnt seem to be possible to login to google voice using OAUTH2 currently as Google Voice is not listed as an API on the google developer console.

**Comment by n8carrier** [comment]
I haven't used this in years, but pretty sure the unofficial API used by pygooglevoice was shut down by Google. Also, to answer my original question, it wasn't ever possible to carry through credentials, because pygooglevoice just makes HTTP requests to the Google Voice site.

**Comment by chris001** [comment]
@n8carrier The GV web interface, used by pygooglevoice, is working fine!  You're right, credentials don't work on the google voice site, it's a web interface which expects to be interacting with the user, not oauth2 credentials.
